### ISSUE TITLE
Scroll behaviour

### ISSUE THREAD

**Issue by mikigoalie** [gfazioli/mantine-picker#1]
First of all, amazing extension!

Noticed that on the demo page, scroll behaviour is not as expected, scrolling doesn't snap on next item and it stops mid scrolls.
Tested on chrome & opera without any extensions or modifications.

Adjusting settings doesn't tweak the unwanted effect.

https://github.com/user-attachments/assets/1491b67e-e4e0-42a1-9733-ae3a597f573b

**Comment by gfazioli** [comment]
@mikigoalie I released a patch, could you try with this latest version? just one more thing, did you try to change the "Wheel Sensitivity"

**Comment by mikigoalie** [comment]
@gfazioli hey, I tried to mess around a bit with source code, but no luck. You were right that it is windows handling the scroll differently, unfortunately your latest commits did not fix it. To answer your question, yes I had tried adjusting settings in story book, but none got rid of that missaligned scroll snap as seen on the clip earlier, feel free to ping me if you needed some more tests.

**Comment by gfazioli** [comment]
@mikigoalie thank you. In the meantime, I tried using Browserstack and was partially able to replicate the issue. Although the operating system and browser were Windows, my mouse is still a Mac....

Currently, the only thing I've noticed is related to the wheel sensitivity.... 

https://github.com/user-attachments/assets/06ac9348-7fc6-40cd-9d6e-7c310c2a335d

I'll keep investigating and get back to you as soon as possible

**Comment by gfazioli** [comment]
@mikigoalie The upcoming v3 release (currently in PR #21) includes several fixes to the wheel scroll behavior that should address this issue:

1. **Passive event listener fix** — The wheel handler is now registered as a native event with `{ passive: false }`, which allows `preventDefault()` to work correctly. Previously, modern browsers would silently ignore `preventDefault()` on passive wheel listeners, causing the scroll to "slip" past items.

2. **Stale closure fix** — The snap-to-nearest logic in the wheel debounce timeout was reading a stale `currentPosition` from the closure. It now reads from a ref (`currentPositionRef.current`), so the snap always targets the correct position.

3. **Windows-specific sensitivity** — The `sensitivity *= 0.2` multiplier for Windows mouse wheels is still in place and has been simplified.

4. **General refactor** — The momentum, drag, and wheel handlers have been refactored with shared `useCallback` functions and proper dependency tracking, which eliminates several edge cases where state could get out of sync.

We'll close this issue once v3 is released and confirmed working on Windows. @mikigoalie, we'd appreciate it if you could test the new version when it's published.

**Comment by gfazioli** [comment]
Hi @mikigoalie, just a friendly ping — [v3.0.0](https://github.com/gfazioli/mantine-picker/releases) is out and includes the wheel scroll fixes I mentioned earlier:

- wheel listener now registered as a native event with `{ passive: false }` so `preventDefault()` actually takes effect
- snap-to-nearest now reads the position from a ref, fixing the stale closure that could leave the wheel mid-item
- Windows-specific sensitivity dampening to compensate for the larger `deltaY` values

Could you give the [updated demo](https://gfazioli.github.io/mantine-picker/) another try on your Windows setup and let me know if the snap behavior is correct now?

If the issue persists, it would help a lot to know:
1. The exact input device (e.g. "Logitech MX Master mouse" / "Microsoft Precision touchpad" / "generic wheel mouse")
2. Whether it also misbehaves with a different mouse on the same machine

I have a hypothesis that the remaining cases are tied to high-DPI mice or Precision touchpads rather than the OS itself, and I have a follow-up fix ready if needed. Thanks!

**Comment by gfazioli** [comment]
Hi @mikigoalie 👋

Closing this one out as resolved — the wheel-scroll fixes shipped in **v3.0.0** and the larger interaction refactor has been stable since. The key changes that addressed your Windows report:

- wheel listener registered as a native event with `{ passive: false }` so `preventDefault()` actually applies
- snap-to-nearest now reads the position from a ref (fixed the stale-closure that left the wheel mid-item)
- Windows-specific sensitivity dampening for the larger `deltaY` values

If you ever hit the misaligned snap again on your setup, please don't hesitate to reopen with the exact input device — happy to dig back in. Thanks a lot for the original report and the patient testing! 🙏
